Find the minimum value of function:

\begin{align}
f{(x_1,x_2)} = -\Bigg|\sin(x_1)\cos(x_2)\exp \bigg( \bigg| 1-\frac{\sqrt{x_1^2 + x_2^2}}{\pi} \bigg|\bigg) \Bigg|
\end{align}

while $ -10 <= x_1 <= 10 $ and $ -10 <= x_2 <= 10 $

In [1]:
import numpy as np
import random

In [2]:
def f(x,y):
    return -(abs(np.sin(x)*np.cos(y)*np.exp(abs(1 - (np.sqrt((x ** 2) + (y ** 2))) / np.pi))))

In [3]:
def fitness(x1,x2):
    return 1/f(x1,x2)

In [4]:
def init():
    return ([random.uniform(-10,10),random.uniform(-10,10)])

In [5]:
def velocity (v_i,phi_cognition,phi_social,p_i, x_i, p_g,VMax):
    """
    :param v_i : vektor velocity untuk partikel ke-i 
    :param p_i : vektor nilai fitness terbaik yang dihasilkan sejauh ini oleh partikel ke-i
    :param x_i : posisi partikel ke-i
    :param p_g : vektor nilai fitness terbaik yang dihasilkan sejauh ini 
                 oleh partikel terbaik dalam topologi ketetanggan
                 
    :param phi_cognition = phi 1 : laju belajar untuk komponen cognition (kecerdasan individu)
    :param phi_social = phi 2: laju belajar untuk koponen social (hubungan social antar individu)     
    
    return :velocity terbaru dari partikel ke-i
    
    """
    r = random.uniform(0,1)
    v = [[]]*len(v_i)
    for d in range (len(v)):
        tmp = v_i[d] + phi_cognition * r * np.subtract(p_i[d],x_i[d]) + phi_social * r * np.subtract(p_g[d],x_i[d])
        v[d] = tmp if (-VMax <= tmp <= VMax) else (tmp/abs(tmp))*VMax
    return v     

In [6]:
X = []
P = []
V = []
x_fitness = []
p_fitness = []
VMax = 2
phi_cognition = 0.5
phi_social = 0.3

n_partikel = 20
for i in range(n_partikel):
    X.append(init())
    P.append(X[-1][:])
    V.append([random.uniform(-VMax,VMax),random.uniform(-VMax,VMax)])
    x_fitness.append([fitness(X[-1][0],X[-1][1]),i])
    p_fitness.append(x_fitness[-1][:])

for iterasi in range (100): #change soon
    for partikel in range (n_partikel):
        x_fitness[partikel][0] = fitness(X[partikel][0],X[partikel][1])
        if (x_fitness[partikel] > p_fitness[partikel]):
            P[partikel] = X[partikel][:]
            p_fitness[partikel] = x_fitness[partikel][:]
    gbest = P[max(p_fitness)[1]]
    for partikel in range (n_partikel):
        V[partikel] = velocity(V[partikel],phi_cognition,phi_social,P[partikel],X[partikel],gbest,VMax)
        X[partikel] = np.add(X[partikel],V[partikel])
        for i in range(len(X[partikel])):
            while X[partikel][i] > 10 or X[partikel][i] < -10:
                X[partikel][i] = random.uniform(-10,10)
#     for i in range (len(X)):
#         print (X[i] , 1/x_fitness[i][0])
#     print ("")
print('coordinate   : ',gbest)
print('minimum value: ',f(gbest[0],gbest[1]))
        
    

coordinate   :  [8.04278443241122, 9.607907695810798]
minimum value:  -19.174792249273906


In [7]:
X

[array([ 9.89369773, -2.18492286]),
 array([ 2.26987511, -0.13558541]),
 array([8.03018089, 8.29001797]),
 array([ 2.1808175 , -8.53166143]),
 array([ 9.04824627, -0.38924338]),
 array([-9.45663412, -8.35376836]),
 array([-0.51705505,  9.77630812]),
 array([-6.7255783 ,  4.35901266]),
 array([-1.1401343 , -4.59914022]),
 array([-0.98677455, -1.10527435]),
 array([ 6.56256253, -3.12676679]),
 array([9.65416537, 6.1638405 ]),
 array([9.98749849, 5.18089351]),
 array([-2.69510725, -4.85718451]),
 array([7.66997066, 7.61935313]),
 array([-5.55444749,  9.584362  ]),
 array([ 3.34494014, -1.55321073]),
 array([-3.2732491 , -1.69463223]),
 array([ 8.27657981, -1.08262907]),
 array([-1.0789739 ,  6.94927803])]

In [8]:
P

[array([ 7.72216912, -6.85450115]),
 array([-3.95379344, -9.04344042]),
 array([7.94699222, 9.53825104]),
 array([8.26602092, 9.70333933]),
 [8.04278443241122, 9.607907695810798],
 array([8.56975065, 9.31490154]),
 array([-8.55075846,  9.8013862 ]),
 array([-8.47809751,  9.97382227]),
 array([ 7.91715053, -9.61106684]),
 [-5.8138756371767, -8.566857523096074],
 array([ 7.9991839 , -9.69333867]),
 array([7.87812331, 9.7111569 ]),
 array([8.26911352, 9.59411624]),
 array([-5.66227623, -9.16467966]),
 array([8.14075502, 9.50678517]),
 array([7.54190066, 9.47717801]),
 array([7.71003823, 9.62044404]),
 array([-7.4872245 , -5.90051148]),
 array([ 8.58483832, -9.43844587]),
 array([8.19489684, 8.96230219])]

In [9]:
V

[[1.9414077885358318, -1.1594860433287062],
 [-2.0, -1.4575958745974864],
 [0.29970802369408633, 2.0],
 [2.0, 2.0],
 [0.5784723467591962, 2.0],
 [1.4047575150849738, 2.0],
 [-1.2435075503696846, 0.015959316425093305],
 [-0.7678807100587248, 2.0],
 [2.0, 0.1422472250159359],
 [1.3832984321544788, -0.9923186934820647],
 [-0.4199597179801461, -0.9746677292331387],
 [2.0, 2.0],
 [1.9585010628519073, 2.0],
 [-0.19965451303715032, -0.9050797721142452],
 [0.12092068066512725, 2.0],
 [2.0, 2.0],
 [2.0, 2.0],
 [0.11428261786717275, 0.1142826757478228],
 [2.0, -0.7302684323912447],
 [2.0, 2.0]]

In [10]:
x_fitness

[[-0.4102329711120885, 0],
 [-2.9446354615180645, 1],
 [-0.1147889226592306, 2],
 [-1.7223929079901887, 3],
 [-0.2770159590614238, 4],
 [-0.28240943525898843, 5],
 [-0.19226578066916256, 6],
 [-1.5593475395171352, 7],
 [-10518.489192737577, 8],
 [-1.1301084093538571, 9],
 [-0.7513962427433246, 10],
 [-0.3320966881332883, 11],
 [-0.17772214499258623, 12],
 [-1.4797316141342842, 13],
 [-0.18093127594432046, 14],
 [-0.35380834423093543, 15],
 [-0.15822388237824395, 16],
 [-13.941037458612417, 17],
 [-59.27721406262579, 18],
 [-28.947931104190967, 19]]

In [11]:
p_fitness

[[-0.12183827841470285, 0],
 [-0.17435023798108393, 1],
 [-0.05281064734378353, 2],
 [-0.05335811108487597, 3],
 [-0.05215180362842612, 4],
 [-0.06448500345125895, 5],
 [-0.06067493440254173, 6],
 [-0.060876981081958756, 7],
 [-0.052645986770397744, 8],
 [-0.34045408585234743, 9],
 [-0.05216475817373626, 10],
 [-0.052942547606309315, 11],
 [-0.05347635213481926, 12],
 [-0.15673549994650765, 13],
 [-0.05292327595574676, 14],
 [-0.0605405082536535, 15],
 [-0.0553158694061172, 16],
 [-0.15099779055522816, 17],
 [-0.06289971241716995, 18],
 [-0.06752027475984734, 19]]